import { Product } from './types'

export const products: Product[] = [
  {
    id: '1',
    slug: 'titan-gan-charger-65w',
    name: 'Titan GaN Charger 65W',
    tagline: 'Aerospace-grade power in your palm',
    description: 'A compact 65W GaN charger machined from aerospace-grade aluminum. Features dual USB-C ports with dynamic power distribution, foldable prongs, and intelligent temperature control. Charges a MacBook Pro from 0-50% in just 28 minutes.',
    price: 69,
    category: 'power',
    useCase: 'commuter',
    materials: ['6061 Aluminum', 'Gallium Nitride', 'Polycarbonate'],
    weight: '98g',
    dimensions: '48 x 48 x 30mm',
    features: ['65W GaN Technology', 'Dual USB-C Ports', 'Foldable Prongs', 'Overheat Protection', 'PD 3.0 / QC 4+ Compatible'],
    images: ['/products/charger-1.jpg', '/products/charger-2.jpg'],
    inStock: true,
  },
  {
    id: '2',
    slug: 'carbon-power-bank-10k',
    name: 'Carbon Power Bank 10K',
    tagline: 'Ultralight 10,000mAh wrapped in forged carbon',
    description: 'A 10,000mAh power bank with a unidirectional carbon fiber shell. Weighs 40% less than traditional power banks. Supports 30W passthrough charging — charge the bank and your devices simultaneously. LED matrix display shows exact remaining capacity.',
    price: 89,
    category: 'power',
    useCase: 'minimalist',
    materials: ['Forged Carbon Fiber', 'Lithium Polymer', 'Aluminum Frame'],
    weight: '152g',
    dimensions: '102 x 62 x 12mm',
    features: ['10,000mAh Capacity', '30W USB-C PD', 'Passthrough Charging', 'LED Capacity Display', 'Air Travel Safe'],
    images: ['/products/powerbank-1.jpg', '/products/powerbank-2.jpg'],
    inStock: true,
  },
  {
    id: '3',
    slug: 'loop-cable-3-in-1',
    name: 'Loop Cable 3-in-1',
    tagline: 'Magnetic self-stowing cable that disappears',
    description: 'A 3-in-1 cable with integrated magnetic loop closure. Braided Kevlar exterior with USB-C, Lightning, and microUSB tips stored in a self-stowing magnetic housing. 1.2m length with integrated cable tie.',
    price: 34,
    compareAtPrice: 45,
    category: 'power',
    useCase: 'creator',
    materials: ['Kevlar Braid', 'Neodymium Magnets', 'Silicone', 'Zinc Alloy'],
    weight: '42g',
    dimensions: '1.2m length (retracted: 15cm)',
    features: ['USB-C + Lightning + microUSB', 'Magnetic Self-Stowing', 'Kevlar Braided', '60W PD Charging', 'Integrated Cable Tie'],
    images: ['/products/cable-1.jpg', '/products/cable-2.jpg'],
    inStock: true,
  },
  {
    id: '4',
    slug: 'mag-dock-traveler',
    name: 'MagDock Traveler',
    tagline: '3-in-1 wireless charging station that folds flat',
    description: 'A folding magnetic charging station for iPhone, AirPods, and Apple Watch. Precision-machined aluminum hinge folds completely flat for travel. 15W MagSafe fast charging with optimized charging profiles.',
    price: 119,
    category: 'power',
    useCase: 'commuter',
    materials: ['CNC Aluminum', 'Silicone Pad', 'Neodymium Magnets'],
    weight: '185g',
    dimensions: '165 x 75 x 18mm (folded)',
    features: ['15W MagSafe', '3-Device Charging', 'Folding Design', 'Nightstand Mode', 'PassThrough USB-C'],
    images: ['/products/magdock-1.jpg', '/products/magdock-2.jpg'],
    inStock: true,
  },
  {
    id: '5',
    slug: 'vegan-leather-cardholder',
    name: 'Veil Cardholder',
    tagline: 'Slim cardholder with RFID-blocking polymer weave',
    description: 'A minimalist cardholder woven from automotive-grade vegan leather and bonded RFID-blocking fabric. Holds up to 8 cards while maintaining a 7mm profile. Patented tension system keeps cards secure yet accessible with one hand.',
    price: 49,
    category: 'carry',
    useCase: 'minimalist',
    materials: ['PU Vegan Leather', 'RFID-Blocking Fabric', 'Elastomer Tension Band'],
    weight: '24g',
    dimensions: '102 x 68 x 7mm',
    features: ['Holds 8 Cards', 'RFID Blocking', 'One-Hand Access', 'Slim 7mm Profile', 'Quick-Draw Slot'],
    images: ['/products/cardholder-1.jpg', '/products/cardholder-2.jpg'],
    inStock: true,
  },
  {
    id: '6',
    slug: 'organizer-pouch',
    name: 'Grid Organizer Pouch',
    tagline: 'Modular cable organiser with laser-cut grid',
    description: 'A laser-cut EDC organizer with a modular elastic grid system. Holds cables, dongles, drives, and tools in a configurable layout. Made from recycled PET ballistic nylon with YKK zippers.',
    price: 39,
    category: 'carry',
    useCase: 'creator',
    materials: ['Recycled PET Ballistic Nylon', 'YKK Zippers', 'Elastic Cord'],
    weight: '68g',
    dimensions: '200 x 130 x 30mm',
    features: ['Modular Grid System', 'YKK Zippers', 'Recycled Materials', 'Fits in Sling Bag', 'Configurable Dividers'],
    images: ['/products/pouch-1.jpg', '/products/pouch-2.jpg'],
    inStock: true,
  },
  {
    id: '7',
    slug: 'sling-pack-mini',
    name: 'Sling Pack Mini',
    tagline: '3L crossbody pack with hidden magnetic closure',
    description: 'A 3L crossbody sling bag with a concealed magnetic Fidlock closure. Quick-access front pocket with built-in key leash, padded tablet sleeve, and hidden back pocket for passport/wallet. Cordura fabric with DWR coating.',
    price: 129,
    category: 'carry',
    useCase: 'commuter',
    materials: ['Cordura Nylon', 'Fidlock Magnetic Buckle', 'YKK AquaGuard'],
    weight: '210g',
    dimensions: '280 x 180 x 80mm',
    features: ['3L Capacity', 'Magnetic Fidlock Closure', 'Padded Tablet Sleeve', 'Hidden Back Pocket', 'DWR Coating'],
    images: ['/products/sling-1.jpg', '/products/sling-2.jpg'],
    inStock: true,
  },
  {
    id: '8',
    slug: 'titanium-key-organizer',
    name: 'Titanium KeyBar',
    tagline: 'Zero-rattle key management with titanium frame',
    description: 'A titanium key organizer that eliminates pocket bulk and key rattle. Holds up to 8 keys with stainless steel screws and nylon washers. Integrated prybar and bottle opener in the frame.',
    price: 59,
    category: 'carry',
    useCase: 'minimalist',
    materials: ['Grade 5 Titanium', 'Stainless Steel Screws', 'Nylon Washers'],
    weight: '38g',
    dimensions: '82 x 32 x 14mm',
    features: ['Holds 8 Keys', 'Zero-Rattle Design', 'Integrated Prybar', 'Bottle Opener', 'Spring-Loaded Key Access'],
    images: ['/products/keybar-1.jpg', '/products/keybar-2.jpg'],
    inStock: true,
  },
  {
    id: '9',
    slug: 'precision-multi-tool',
    name: 'Precision Bit Driver',
    tagline: '20 precision bits in a machined aluminum cylinder',
    description: 'A precision bit driver with 20 hardened steel bits stored in a CNC-machined 6061 aluminum cylinder. Magnetic bit retention, knurled grip, and a ratcheting mechanism for precise torque control. Includes Phillips, Torx, Hex, and flathead bits.',
    price: 79,
    category: 'utility',
    useCase: 'creator',
    materials: ['6061 Aluminum', 'S2 Steel Bits', 'Neodymium Magnets'],
    weight: '96g',
    dimensions: '100 x 20mm (cylinder)',
    features: ['20 Precision Bits', 'Ratcheting Mechanism', 'Magnetic Retention', 'Knurled Grip', 'Slide-Out Bit Storage'],
    images: ['/products/tool-1.jpg', '/products/tool-2.jpg'],
    inStock: true,
  },
  {
    id: '10',
    slug: 'edc-flashlight-ti',
    name: 'Pulse EDC Light',
    tagline: '1000-lumen titanium flashlight the size of a AAA battery',
    description: 'An everyday carry flashlight machined from Grade 5 titanium. 1000 lumen max output with 5 brightness modes. USB-C rechargeable with magnetic tail cap for hands-free operation. Waterproof to 50m.',
    price: 99,
    category: 'utility',
    useCase: 'commuter',
    materials: ['Grade 5 Titanium', 'Optical Glass', 'Copper Driver'],
    weight: '38g',
    dimensions: '68 x 18mm',
    features: ['1000 Lumens', '5 Brightness Modes', 'USB-C Rechargeable', 'Magnetic Tail Cap', 'IPX8 Waterproof'],
    images: ['/products/flashlight-1.jpg', '/products/flashlight-2.jpg'],
    inStock: true,
  },
  {
    id: '11',
    slug: 'field-notes-cover-ti',
    name: 'Field Cover Titanium',
    tagline: 'Pocket notebook armor with integrated pen loop',
    description: 'A pocket-sized titanium cover for Field Notes / passport-size notebooks. Precision-fit with a spring steel clip that doubles as a page marker. Integrated pen loop fits most bolt-action pens. Adds only 2mm to notebook thickness.',
    price: 45,
    category: 'utility',
    useCase: 'minimalist',
    materials: ['Grade 2 Titanium', 'Spring Steel Clip'],
    weight: '28g',
    dimensions: '140 x 90 x 2mm',
    features: ['Fits Field Notes / Passport', 'Spring Steel Pen Clip', 'Ultra-Slim Profile', 'Page Marker', 'Corrosion Resistant'],
    images: ['/products/fieldcover-1.jpg', '/products/fieldcover-2.jpg'],
    inStock: true,
  },
  {
    id: '12',
    slug: 'cable-organizer-clips',
    name: 'Cable Catch Set',
    tagline: 'Magnetic cable clips that stick anywhere',
    description: 'A set of 4 magnetic cable management clips with 3M automotive-grade adhesive. Neodymium N52 magnets hold cables securely. Low-profile design in matte aluminum. Each clip handles up to 3 cables.',
    price: 24,
    category: 'utility',
    useCase: 'creator',
    materials: ['Aluminum Housing', 'N52 Neodymium Magnets', '3M VHB Adhesive'],
    weight: '8g (each)',
    dimensions: '20 x 10 x 8mm',
    features: ['Set of 4', 'N52 Magnets', '3M Adhesive Backing', 'Holds 3 Cables Each', 'Silicone Cable Grip'],
    images: ['/products/clips-1.jpg', '/products/clips-2.jpg'],
    inStock: true,
  },
]

export const categories = [
  { id: 'all', label: 'All', icon: '✦' },
  { id: 'power', label: 'Power', icon: '⚡' },
  { id: 'carry', label: 'Carry', icon: '⊞' },
  { id: 'utility', label: 'Utility', icon: '⚙' },
] as const

export const useCases = [
  { id: 'all', label: 'All' },
  { id: 'commuter', label: 'The Commuter' },
  { id: 'minimalist', label: 'The Minimalist' },
  { id: 'creator', label: 'The Creator' },
] as const

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getProductsByCategory(category: string): Product[] {
  if (category === 'all') return products
  return products.filter((p) => p.category === category)
}
